In [1]:
import numpy as np

- scalar : 상수값 (10, 3.14, 'korea')
- vector(1차원) : [10,20,30]
- matrix(2차원) : [ [10,20,30], [10,20,30] ] => 2 by 3 행렬  
- 3차원 : [ [ [10,20,30], [10,20,30] ] , [ [10,20,30], [10,20,30] ] ] => 2 x 2 x 3 

- 객체 : 속성 + 메소드
- 객체.속성
- 객체.메소드()

#### ndarray 

In [2]:
# 1차원 리스트로 출력.
arr1 = np.array([10,20,30])
print(f' Type : {type(arr1)}')
print('-'*33)
print(arr1)

 Type : <class 'numpy.ndarray'>
---------------------------------
[10 20 30]


In [3]:
# 2차원 행렬로 출력.
arr2 = np.array( [ [10,20,30], [10,20,30] ] )
print(f' Type : {type(arr2)}')
print('-'*33)
arr2

 Type : <class 'numpy.ndarray'>
---------------------------------


array([[10, 20, 30],
       [10, 20, 30]])

In [4]:
# 1 <= arr < 11 1씩 증가 => arange() : 수열을 만드는 함수.
arr3 = np.arange( 1, 11, 1) 
print(f' Type : {type(arr3)}')
print('-'*48)
arr3

 Type : <class 'numpy.ndarray'>
------------------------------------------------


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# np.random.randint() : 난수를 만드는 함수.
arr4 = np.random.randint(1, 11, 5)
print(f' Type : {type(arr4)}')
print('-'*33)
arr4

 Type : <class 'numpy.ndarray'>
---------------------------------


array([ 6,  3, 10,  1,  3])

In [6]:
# => 튜플로 구성하면, 3행 2열 형태로 난수를 만들수도 있음.
arr5 = np.random.randint( 1, 11, (3, 2) )
print(f' Type : {type(arr4)}')
print('-'*33)
arr5

 Type : <class 'numpy.ndarray'>
---------------------------------


array([[7, 3],
       [9, 2],
       [5, 6]])

In [7]:
# 0 ~ 1 상이의 실수값 반환. => np.random.rand(차원), 차원 : (2, 3)으로도 가능.
np.random.rand(5)  

array([0.03503337, 0.76463204, 0.37730863, 0.1267022 , 0.22851324])

In [8]:
# randn() : 정규분포로부터 값을 추출. 
np.random.randn(5)

array([-1.98030662,  1.05475338, -0.61060105, -0.75052942,  0.37104011])

In [9]:
# np.random.choice() : 리스트 값 중에서 임의로 몇개를 설정 가능. 중복도 가능.
np.random.choice([1,2,3,4,5], 3) 

array([3, 4, 1])

In [10]:
# replace = True (디폴트값) = > 복원 추출. False : 비복원 추출.
np.random.choice(np.arange(11), 5) 

array([2, 0, 5, 2, 5])

In [11]:
# np.random.shuffle() : 데이터를 임의로 재배치.
arr6 = np.arange(11)
np.random.shuffle(arr6)
arr6  

array([ 7,  5,  4,  2,  8,  6,  3,  9,  1, 10,  0])

In [12]:
# np.array([1,2,3,4,5], dtype=np, int32)
np.int32([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
np.int64([1,2,3,4,5])

array([1, 2, 3, 4, 5], dtype=int64)

In [14]:
# 실수값(float)으로 구성된 ndarray를 만들어줌.
np.float32([1,2,3,4,5]) 

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
np.array([1,2,3,4,5], dtype = np.str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
# ones() : 1을 지정한 개수만큼 만들어주는 함수.
np.ones(shape = 7)  

array([1., 1., 1., 1., 1., 1., 1.])

In [17]:
# 행렬 형태로도 가능.
np.ones(shape=(3,3))  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# zeros() : 0을 지정한 개수만큼 만들어주는 함수.
np.zeros(shape = 5)  

array([0., 0., 0., 0., 0.])

In [19]:
# 희소행렬(Sparse matrix).
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# 지정한 범위(1 ~ 10)에서 지정한 개수만큼 분할해서 값을 출력.
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
# log의 개념이 들어갈 뿐 linspace() 기능은 유사함.
np.logspace(1, 10, 2)

array([1.e+01, 1.e+10])

In [22]:
# np.unique() : 배열 내 중복된 원소 제거 후 유일한 원소를 정렬하여 반환.
# return_counts=True : 중복 제거.
v, c = np.unique( [1,2,2,3,3,3,4,4,5,5] , return_counts=True ) 
print(v)
print(c)

[1 2 3 4 5]
[1 2 3 2 2]


In [23]:
# zip() : 동일한 개수로 이루어진 자료형을 묶어 주는 역할을 하는 함수.
for a, b in zip(v, c) :
    print(a, b)

1 1
2 2
3 3
4 2
5 2
