In [17]:
import numpy as np

In [2]:
edit mode(연두색): tab(자동완성), shift+tab(아규먼트)
ctrl + enter (코드 실행), shift + enter (코드실행후 아래로 셀이동) ,esc(커맨드모드 전환),crtl + /(주석 및 제거)

command mode(하늘색): enter(edit mode), a(위에 셀추가), b(아래에 셀추가), x(셀 삭제), z(삭제 취소), m(해당셀 주석셀), y(코드셀)
    
프린트 없이 출력은 jupiter 자체 스타일 적용 -> 그리고 맨마지막 것만 출력된다

SyntaxError: invalid syntax (<ipython-input-2-60f9d95a3476>, line 1)

# 여기는 주석셀
## 테스트1
### 테스트2
<h1>테스트1</h1>
<h2>테스트1</h2>
<img src="image/a.png>

In [10]:
print('hello')

hello


In [6]:
a=10
b=20
# print(a)
a
b

20

## 용어정리

### scalar : 상수값 (10, 3.14, 'korea')
### vector(1차원): [10,20,30]
### matrix(2차원): [ [10,20,30], [10,20,30] ] : 2 by 3 행렬  
### 3차원 : [ [ [10,20,30], [10,20,30] ] , [ [10,20,30], [10,20,30] ] ] 2 x 2 x 3

In [ ]:
객체: 속성 + 메소드
객체.속성
객체.메소드()

In [18]:
arr1 = np.array([10,20,30])
print(type(arr1))
print(arr1)
arr1

<class 'numpy.ndarray'>
[10 20 30]


array([10, 20, 30])

In [20]:
arr2 = np.array( [ [10,20,30], [10,20,30] ] )
print(arr2)
arr2

[[10 20 30]
 [10 20 30]]


array([[10, 20, 30],
       [10, 20, 30]])

2.ndarray 생성방법

In [27]:
arr3 = np.arange( 1,11,1 ) # 1<= arr <11 1씩 증가  -> 수열을 만드는 함수가 arange
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr4 = np.arange( 1,11,2 ) # 1<= arr <11 2씩 증가
arr4

array([1, 3, 5, 7, 9])

1. 백문이 불여일타
2. 코딩은 학습이아니라 연습이다

3. ndarray 생성방법

In [37]:
arr5 = np.random.randint(1,11,5)   # <- 난수 만드는 함수
arr5

array([7, 3, 9, 4, 4])

In [38]:
arr6 = np.random.randint(1,11,(3,2))   # <- 3행 2열로 난수 만드는 함수
arr6

array([[ 4,  3],
       [ 3, 10],
       [ 2, 10]])

In [39]:
np.random.rand(5)  # 0~1 상이의 실수값 반환 np.random.rand(차원) 차원=>(2,3)으로도 가능

array([0.78603096, 0.28193137, 0.44944724, 0.37072389, 0.70260929])

In [41]:
np.random.randn(5) #  standard normal 를 만들어줌 -> 단, n : large

array([ 0.87578685, -0.46661062,  0.86951388, -0.83446539,  2.28723186])

In [42]:
np.random.randn(2,3) # 평균이 2이고 표준편차가 3인 ??

array([[ 0.69145293, -1.33223679, -0.1672707 ],
       [ 0.36610104, -0.27070368, -0.68854954]])

In [48]:
np.random.choice([1,2,3,4,5],3) # 리스트 값중에서 임의로 3개 설정 가능. 중복가능

array([2, 2, 3])

In [49]:
np.random.choice(np.arange(11),5) # replace = True (디폴트값) = > 복원 추출

array([ 5,  3, 10, 10,  7])

In [53]:
arr6 = np.arange(11)
np.random.shuffle(arr6)
arr6  # 데이터가 임의로 재배치가 된다

array([ 5,  8,  2,  3,  9, 10,  6,  0,  7,  4,  1])

4. ndarray 생성방법

In [55]:
np.int32([1,2,3,4,5])
# np.array([1,2,3,4,5], dtype=np, int32)

array([1, 2, 3, 4, 5])

In [56]:
np.int64([1,2,3,4,5])

array([1, 2, 3, 4, 5], dtype=int64)

In [57]:
np.float32([1,2,3,4,5])  # 실수값으로 구성된 ndarray를 만들어줌

array([1., 2., 3., 4., 5.], dtype=float32)

In [59]:
np.array([1,2,3,4,5], dtype=np.str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [60]:
np.ones(shape=3)  

array([1., 1., 1.])

In [61]:
np.ones(shape=(3,3))  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.zeros(shape=3)  

array([0., 0., 0.])

In [64]:
np.eye(3) # 희소행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [68]:
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [75]:
v, c = np.unique( [1,2,2,3,3,3,4,4,5,5] ,return_counts=True) # 중복제거
print(v)
print(c)

[1 2 3 4 5]
[1 2 3 2 2]


In [76]:
for a,b in zip(v,c):
    print(a,b)

1 1
2 2
3 3
4 2
5 2
