In [1]:
import numpy as np

In [2]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

In [3]:
# arr의 형태.
arr.dtype

dtype('int32')

In [4]:
# arr의 크기.
arr.size

5

In [5]:
# arr의 차원.
arr.ndim

1

In [6]:
# arr의 shape.
arr.shape

(5,)

In [7]:
arr2 = np.array( [[11, 22],[33, 44],[55, 66]] )
arr2

array([[11, 22],
       [33, 44],
       [55, 66]])

In [8]:
# 3행(arr의 길이.) 2열의 shape임을 알 수 있음.
arr2.shape

(3, 2)

In [9]:
# arr의 크기.(즉, 원소의 개수로 길이와는 다름.)
arr2.size

6

In [10]:
# 전치 행렬 개념. 즉 Transpose로 T() : 2 x 3 행렬 변환.
print(arr2.T)
arr2.T.shape

[[11 33 55]
 [22 44 66]]


(2, 3)

#### 형변환

In [11]:
# 현재 arr의 형태.
arr.dtype

dtype('int32')

In [12]:
# int64 형으로 변환.
arr = arr.astype(np.int64)
arr.dtype

dtype('int64')

In [13]:
# float32(실수) 형으로 변환.
arr.astype(np.float32)

array([11., 22., 33., 44., 55.], dtype=float32)

In [14]:
arr3 = np.array(range(1, 7))
arr3

array([1, 2, 3, 4, 5, 6])

In [15]:
# reshape() : 원하는 shape의 형태로 변환.
arr3.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# -1의 의미는 뒤(3)에 형태를 맞추고 나머지는 알아서 결정해주는 것을 의미
arr3.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 2차원 데이터인 경우.
# 2행 3열 리스트를 만들어줌.
arr4 = np.array( [ [1,2,3], [7,5,2], [10,1,8], [6,3,4] ] )
arr4.reshape(-1, 2, 3)
arr4

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])