In [1]:
import numpy as np

In [3]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.size

5

In [7]:
arr.shape

(5,)

In [9]:
arr.ndim

1

In [11]:
arr1 = np.array([[11,22],[33,44],[55,66]])
arr1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [12]:
arr1.shape

(3, 2)

In [13]:
arr1.size

6

In [15]:
arr1.T  # 전치 행렬 개념 즉 transpose

array([[11, 33, 55],
       [22, 44, 66]])

## 형변환

In [17]:
arr.dtype

dtype('int32')

In [26]:
arr = arr.astype(np.int64)

In [27]:
arr.dtype

dtype('int64')

In [25]:
arr

array([11, 22, 33, 44, 55])

In [24]:
arr.astype(np.float32)

array([11., 22., 33., 44., 55.], dtype=float32)

In [29]:
arr2 = np.array([1,2,3,4,5,6])
arr2

array([1, 2, 3, 4, 5, 6])

In [30]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
arr2.reshape(-1,3)  # -1 (알아서 결정)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2

array([1, 2, 3, 4, 5, 6])