In [1]:
import numpy as np

In [2]:
arr = np.array(range(11, 56, 11))
arr

array([11, 22, 33, 44, 55])

In [3]:
arr[0]

11

In [4]:
# []를 통해 가져오고 싶은 요소들만을 골라서 가져올 수 있음.
arr[ [0, 2, 3] ]

array([11, 33, 44])

#### Slicing

In [5]:
# [ 시작 : 끝 : 증가치 ]
# 1 <= inx < 4 
arr[1 : 4 : 2]

array([22, 44])

In [6]:
arr[ : 4 ]

array([11, 22, 33, 44])

In [7]:
arr[-1]

55

In [8]:
# 0 <= index < -1(마지막 숫자를 제외한다는 의미.)
arr[ : -1 ] 

array([11, 22, 33, 44])

In [9]:
# -1, -2, -3 번째로 단순히 거꾸로 계산하는 것을 의미.
arr[-1 : -4 : -1] 

array([55, 44, 33])

In [10]:
# 2차원 데이터인 경우.
arr2 = np.array( [ [1,2,3], [7,5,2], [10,1,8], [6,3,4] ] )
arr2 

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [11]:
# [면, 행, 열]
# 1행만 제거.
arr2[[0, 2, 3]]

array([[ 1,  2,  3],
       [10,  1,  8],
       [ 6,  3,  4]])

In [12]:
# 1행, 2행만 가져옴.
arr2[1 : 3]

array([[ 7,  5,  2],
       [10,  1,  8]])

In [13]:
# 1행, 2행, 3행을 가져오되, 0열과 2열만 가져옴.
arr2[1:, [0, 2] ]

array([[ 7,  2],
       [10,  8],
       [ 6,  4]])

In [14]:
# -1열(마지막 열)만 제외하고 가져옴.
arr2[ : , :-1]

array([[ 1,  2],
       [ 7,  5],
       [10,  1],
       [ 6,  3]])

In [15]:
# -1열(마지막 열)만 가져옴. 
arr2[ :, [-1]]

array([[3],
       [2],
       [8],
       [4]])

#### Boolean indexing

In [16]:
arr[[True, True, False, False, True]]

array([11, 22, 55])

In [17]:
# 2차원 데이터에서 TRUE인 행만을 표시. 열 단위는 존재하지 않음.
arr2[[True, True, False, True]] 

array([[1, 2, 3],
       [7, 5, 2],
       [6, 3, 4]])

#### 연산( 산술, 관계, 논리)
- element wise (요소별 연산)

In [18]:
arr + 2

array([13, 24, 35, 46, 57])

In [19]:
arr * 2

array([ 22,  44,  66,  88, 110])

In [20]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [21]:
arr + arr1

array([12, 24, 36, 48, 60])

In [22]:
# 연봉데이터가 있을 때 각 연봉에 대한 세금 3.3을제한 실수령액을 구하시오.
salary = np.array( [1000, 2000, 3000, 4000, 5000] )
salary*(1-0.033)

array([ 967., 1934., 2901., 3868., 4835.])

#### 관계 연산자

In [23]:
# element wise 하게 결과가 출력되는 것을 알 수 있으며, 관계 연산자이기에, T, F의 형태로 출력됨.
arr > 30 

array([False, False,  True,  True,  True])

In [24]:
# 관계 연산자의 위와 같은 결과를 이용하여 Boolean indexing을 적용 시킬 수 있음.
arr[ arr > 30 ]

array([33, 44, 55])

In [25]:
# == : 동일함을 의미.
a = arr == 44

In [26]:
arr[a]

array([44])

#### 논리 연산자
- and := & 
-  or := | 
- not := ~

In [27]:
# 반드시 () 할 필요가 있음.
( arr == 11 ) | ( arr == 55 )

array([ True, False, False, False,  True])

In [28]:
( arr > 20 ) & ( arr < 50 )

array([False,  True,  True,  True, False])

In [29]:
~( ( arr==11 ) | ( arr==55 ) )

array([False,  True,  True,  True, False])

In [30]:
# 2차원도 1차원과 유사하게 적용됨.
arr2[ :,0] > 5

array([False,  True,  True,  True])

In [31]:
arr2[(arr2[:,1] >= 3) & (arr2[:,1] <= 7)]

array([[7, 5, 2],
       [6, 3, 4]])

In [32]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])
name

array(['홍길동', '김철수', '임꺽정', '김철이', '이황'], dtype='<U3')

In [33]:
# [n for 항목1 in 반복가능객체1 if 조건문1 in n]
[ n for n in name if '철' in n ]

['김철수', '김철이']