In [1]:
import numpy as np

In [2]:
arr = np.array(range(11, 56, 11))
arr

array([11, 22, 33, 44, 55])

In [3]:
arr[0]

11

In [4]:
# []를 통해 가져오고 싶은 요소들만을 골라서 가져올 수 있음.
arr[ [0, 2, 3] ]

array([11, 33, 44])

#### Boolean indexing

In [5]:
arr[[True, True, False, False, True]]

array([11, 22, 55])

#### Slicing

In [6]:
# [ 시작 : 끝 : 증가치 ]
# 1 <= inx < 4 
arr[1 : 4 : 2]

array([22, 44])

In [7]:
arr[ : 4 ]

array([11, 22, 33, 44])

In [8]:
arr[-1]

55

In [9]:
# 0 <= index < -1(마지막 숫자를 제외한다는 의미.)
arr[ : -1 ] 

array([11, 22, 33, 44])

In [10]:
# -1, -2, -3 번째로 단순히 거꾸로 계산하는 것을 의미.
arr[-1 : -4 : -1] 

array([55, 44, 33])

#### 연산( 산술, 관계, 논리)
- element wise (요소별 연산)

In [11]:
arr + 2

array([13, 24, 35, 46, 57])

In [12]:
arr * 2

array([ 22,  44,  66,  88, 110])

In [13]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [14]:
arr + arr1

array([12, 24, 36, 48, 60])

In [15]:
# 연봉데이터가 있을 때 각 연봉에 대한 세금 3.3을제한 실수령액을 구하시오.
salary = np.array( [1000, 2000, 3000, 4000, 5000] )
salary*(1-0.033)

array([ 967., 1934., 2901., 3868., 4835.])

#### 관계 연산자

In [16]:
# element wise 하게 결과가 출력되는 것을 알 수 있으며, 관계 연산자이기에, T, F의 형태로 출력됨.
arr > 30 

array([False, False,  True,  True,  True])

In [17]:
# 관계 연산자의 위와 같은 결과를 이용하여 Boolean indexing을 적용 시킬 수 있음.
arr[ arr > 30 ]

array([33, 44, 55])

In [18]:
# == : 동일함을 의미.
a = arr == 44

In [19]:
arr[a]

array([44])

#### 논리 연산자
- and := & 
-  or := | 
- not := ~

In [20]:
# 반드시 () 할 필요가 있음.
( arr == 11 ) | ( arr == 55 )

array([ True, False, False, False,  True])

In [21]:
( arr > 20 ) & ( arr < 50 )

array([False,  True,  True,  True, False])

In [22]:
~( ( arr==11 ) | ( arr==55 ) )

array([False,  True,  True,  True, False])

In [23]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])
name

array(['홍길동', '김철수', '임꺽정', '김철이', '이황'], dtype='<U3')

In [24]:
# [n for 항목1 in 반복가능객체1 if 조건문1 in n]
[ n for n in name if '철' in n ]

['김철수', '김철이']