In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

### 추가

In [35]:
arr = np.append(arr, [100,200])  # 추가 
arr

array([ 11,  22,  33,  44,  55, 100, 200])

In [5]:
np.insert(arr,1,[1,2])

array([11,  1,  2, 22, 33, 44, 55])

### 수정

In [7]:
arr[0]=111

In [8]:
arr

array([111,  22,  33,  44,  55])

In [10]:
arr[1:3]=[222,333]
arr

array([111, 222, 333,  44,  55])

In [13]:
arr[3:5] = arr[3:5] + 2
arr

array([111, 222, 333,  48,  59])

In [37]:
#200보다 큰데이터에 대해 기존값에 
#2를 더한 것으로 수정하시요
arr[ arr > 200 ] = arr[ arr > 200 ] + 2
arr

array([ 11,  22,  33,  44,  55, 100, 200])

## 삭제

In [38]:
np.delete(arr, [0,2])

array([ 22,  44,  55, 100, 200])

In [39]:
np.where(arr<100)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [62]:
a = np.where(arr>=30)
np.delete(arr, a)

array([11, 22])

## 조건별 데이터 연산

In [41]:
np.where(arr>100, 'A',"B")

array(['B', 'B', 'B', 'B', 'B', 'B', 'A'], dtype='<U1')

In [44]:
conList = [arr>200, arr>100,arr>0]
choicelist = ['A', 'B', 'C']
np.select(conList, choicelist)

array(['C', 'C', 'C', 'C', 'C', 'C', 'B'], dtype='<U11')

In [43]:
arr

array([ 11,  22,  33,  44,  55, 100, 200])

## 정렬(sort)

In [46]:
np.sort(arr)  # 오름 차순

array([ 11,  22,  33,  44,  55, 100, 200])

In [47]:
np.sort(arr)[-1::-1]  # 내림 차순

array([200, 100,  55,  44,  33,  22,  11])

In [50]:
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [51]:
arr[np.argsort(arr)]

array([ 11,  22,  33,  44,  55, 100, 200])

In [57]:
name = np.array(['홍길동','김철수','임꺽정','김이철','철이임'])

In [59]:
np.char.find(name, sub='철')>=0   # 찾는 문자열의 인덱스를 얻어 온다.

array([False,  True, False,  True,  True])

In [60]:
name[np.char.find(name, sub='철')>=0]

array(['김철수', '김이철', '철이임'], dtype='<U3')

https://numpy.org/doc/stable/reference/routines.char.html