Numpy 참고 사이트 : https://numpy.org/doc/stable/reference/routines.char.html

In [2]:
import numpy as np

In [3]:
# 이용할 데이터 만들기.
arr = np.array(range(11, 56, 11))
arr

array([11, 22, 33, 44, 55])

#### 추가

In [35]:
# 추가. append() : 추가시키는 함수. 값을 담아주는 함수.
arr = np.append(arr, [100, 200]) 
arr

array([ 11,  22,  33,  44,  55, 100, 200])

In [4]:
# 추가. insert() : 어떤 데이터에 몇 번째 자리에 어떤 값들을 추가시킬 수 있는 함수.
np.insert( arr, 0, [1, 2] )

array([ 1,  2, 11, 22, 33, 44, 55])

#### 수정

In [5]:
arr[0] = 111
arr

array([111,  22,  33,  44,  55])

In [7]:
arr[ 1 : 3 ] = [222, 333]
arr

array([111, 222, 333,  44,  55])

In [8]:
arr[ 3 : 5] = arr[3 : 5] + 2
arr

array([111, 222, 333,  46,  57])

In [15]:
# 200보다 큰 데이터에 대해 기존값에 2를 더한 것으로 수정하시오.
arr = np.array(range(1, 501, 50))
arr[ arr > 200 ] = arr[ arr > 200 ] + 2
arr

array([  1,  51, 101, 151, 203, 253, 303, 353, 403, 453])

#### 삭제

In [21]:
# 30보다 작은 arr의 인덱스 위치를 반환해줌.
np.where(arr < 30)

(array([0, 1], dtype=int64),)

In [20]:
# 관계 연산자를 이용한 제거.
a = np.where(arr < 30)
np.delete(arr, a)

array([33, 44, 55])

#### 검색

In [30]:
# 조건에 따른 문자로 반환.
np.where( arr > 40, 'A', 'B')

array(['B', 'B', 'B', 'A', 'A'], dtype='<U1')

In [31]:
# select() : 조건에 따른 검색 및 변환이 가능.
arr = np.array(range(1, 501, 50))
conList = [arr > 200, arr > 100, arr > 0]
choicelist = ['A', 'B', 'C']
np.select(conList, choicelist)

array(['C', 'C', 'B', 'B', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U11')

#### 정렬

In [32]:
# 오름 차순.
np.sort(arr) 

array([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [38]:
# 내림 차순.
np.sort(arr)[:: -1] 

array([451, 401, 351, 301, 251, 201, 151, 101,  51,   1])

In [39]:
# np.argsort(arr, axis=-1, kind=None, order=None) : 넘파이 배열의 원소를 오름차순으로 정렬하는 함수.
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [46]:
# -로 설정하면 내림차순으로도 정렬이 가능.
arr[ np.argsort(-arr) ]

array([451, 401, 351, 301, 251, 201, 151, 101,  51,   1])

In [50]:
name = np.array(['홍길동', '김철수', '임꺽정', '김이철', '철이임'])

# 찾는 문자열의 인덱스를 얻어옴.
np.char.find(name, sub='철') >= 0 

# Boolean indexing
name[ np.char.find(name, sub='철') >= 0 ]

array(['김철수', '김이철', '철이임'], dtype='<U3')