Numpy 참고 사이트 : https://numpy.org/doc/stable/reference/routines.char.html

In [1]:
import numpy as np

In [2]:
# 이용할 데이터 만들기.
arr = np.array(range(11, 56, 11))
arr

array([11, 22, 33, 44, 55])

#### 추가

In [3]:
# 추가. append() : 추가시키는 함수. 값을 담아주는 함수.
arr = np.append(arr, [100, 200]) 
arr

array([ 11,  22,  33,  44,  55, 100, 200])

In [4]:
# 추가. insert() : 어떤 데이터에 몇 번째 자리에 어떤 값들을 추가시킬 수 있는 함수.
np.insert( arr, 0, [1, 2] )

array([  1,   2,  11,  22,  33,  44,  55, 100, 200])

In [5]:
ax = np.array( [[1,2],[3,4]])
ay = np.array( [[5,6],[7,8]])

In [6]:
ax

array([[1, 2],
       [3, 4]])

In [7]:
# axis 인자가 None 상태라 1차원으로 풀어버림.
np.append(ax, ay)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# axis=0 : row(행)으로 추가.
np.append(ax, ay, axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
# axis=1 : col(열)로 추가.
np.append(ax, ay, axis=1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
# n개 이상의 추가할 값이 존재시 hstack를 통해 row(행)에 추가.
np.vstack((ax, ay))      

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# n개 이상의 추가할 값이 존재시 hstack를 통해 col에 추가.
np.hstack((ax, ay))       

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### 수정

In [12]:
arr[0] = 111
arr

array([111,  22,  33,  44,  55, 100, 200])

In [13]:
arr[ 1 : 3 ] = [222, 333]
arr

array([111, 222, 333,  44,  55, 100, 200])

In [14]:
arr[ 3 : 5] = arr[3 : 5] + 2
arr

array([111, 222, 333,  46,  57, 100, 200])

In [15]:
# 200보다 큰 데이터에 대해 기존값에 2를 더한 것으로 수정하시오.
arr = np.array(range(1, 501, 50))
arr[ arr > 200 ] = arr[ arr > 200 ] + 2
arr

array([  1,  51, 101, 151, 203, 253, 303, 353, 403, 453])

#### 삭제

In [16]:
# 30보다 작은 arr의 인덱스 위치를 반환해줌.
np.where(arr < 30)

(array([0], dtype=int64),)

In [17]:
# 관계 연산자를 이용한 제거.
a = np.where(arr < 30)
np.delete(arr, a)

array([ 51, 101, 151, 203, 253, 303, 353, 403, 453])

In [18]:
# 2차원 데이터인 경우.
arr2 = np.array( [ [1,2,3], [7,5,2], [10,1,8], [6,3,4] ] )

# axis=0 : row(행), axis=1 : col(열) 기준으로 판단하며 삭제.
np.delete( arr2, [0, 2], axis=0 )   

array([[7, 5, 2],
       [6, 3, 4]])

#### 검색

In [19]:
# 조건에 따른 문자로 반환.
np.where( arr > 40, 'A', 'B')

array(['B', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [20]:
# select() : 조건에 따른 검색 및 변환이 가능.
arr = np.array(range(1, 501, 50))
conList = [arr > 200, arr > 100, arr > 0]
choicelist = ['A', 'B', 'C']
np.select(conList, choicelist)

array(['C', 'C', 'B', 'B', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U11')

#### 정렬

In [21]:
# 오름 차순.
np.sort(arr) 

array([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [22]:
# 내림 차순.
np.sort(arr)[:: -1] 

array([451, 401, 351, 301, 251, 201, 151, 101,  51,   1])

In [23]:
# np.argsort(arr, axis=-1, kind=None, order=None) : 넘파이 배열의 원소를 오름차순으로 정렬하는 함수.
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [24]:
# -로 설정하면 내림차순으로도 정렬이 가능.
arr[ np.argsort(-arr) ]

array([451, 401, 351, 301, 251, 201, 151, 101,  51,   1])

In [25]:
# axis=None 이면 1차원으로 오름차순 정렬.
np.sort(arr2, axis=None)

array([ 1,  1,  2,  2,  3,  3,  4,  5,  6,  7,  8, 10])

In [26]:
# axis=0 : row(행), axis=1 : col(열) 기준으로 판단하며 정렬.
np.sort(arr2, axis=0)  

array([[ 1,  1,  2],
       [ 6,  2,  3],
       [ 7,  3,  4],
       [10,  5,  8]])

In [27]:
name = np.array(['홍길동', '김철수', '임꺽정', '김이철', '철이임'])

# 찾는 문자열의 인덱스를 얻어옴.
np.char.find(name, sub='철') >= 0 

# Boolean indexing
name[ np.char.find(name, sub='철') >= 0 ]

array(['김철수', '김이철', '철이임'], dtype='<U3')