In [1]:
import numpy as np

#### ndarray 객체의 멤버함수 + np의 함수

In [2]:
# 사용할 데이터 만들기.
arr = np.array(range(11, 56, 11))
arr

array([11, 22, 33, 44, 55])

In [3]:
# 합.
arr.sum()
np.sum(arr)

165

In [4]:
# 평균.
arr.mean()
np.mean(arr)

33.0

In [5]:
# 중앙값.
np.median(arr)         

33.0

In [6]:
# 표준편차.
arr.std()
np.std(arr)  

15.556349186104045

In [7]:
# 최대값.
arr.max()
np.max(arr)      

55

In [8]:
# 최소값.
arr.min()
np.min(arr)      

11

In [9]:
# 가장 큰 값의 index => 즉 55의 인덱스 값을 나타냄.
arr.argmax()
np.argmax(arr)  

4

In [10]:
# 가장 작은 값의 index => 즉 11의 인덱스 값을 나타냄.
arr.argmin()
np.argmin(arr)  

0

In [11]:
# np.quantile() : 100분위수에 해당하는 값을 찾아낼 수 있음.
# 데이터를 정렬했을 떄 50% 해당값 
np.quantile(arr, 0.5)             

33.0

In [12]:
# 4분위수 값.(Q1, Q2, Q3)
np.quantile(arr, [0.25, 0.5, 0.75])    

array([22., 33., 44.])

In [13]:
# np.quantile()와는 단위의 차이만 존재할 뿐 기능은 같음.
np.percentile(arr, [25, 50, 75])    

array([22., 33., 44.])

#### 문제 1

- 1. 국어점수가 50점 이상 80점 이하인 값을 구하시오.
- 2. 국어점수의 평균을 구하시오.
- 3. 국어점수의 총합을 구하시오.
- 4. 국어점수가 40점 이하인 데이터를 삭제하시오.
- 5. 국어점수가 50점 이상인 데이터에 가산점 10%를 부여하시오.
- 6. 국어점수 top5를 구하시오.
- 7. 국어점수가 70점이상이면 '합격', 아니면 '불합격'으로 아래와 같이 출력하시오.

In [14]:
# 사용할 국어 점수 데이터.
kor = np.array( [60, 55, 70, 30, 20, 90] )

print('< 결과 >')
print('='*27)

# 1번 문항.
print(f'조건 : {kor[(kor >= 50) & (kor <= 80)]}')
print('-'*27)

# 2번 문항.
print(f'평균 : {round(kor.mean(), 3)}')
print('-'*27)

# 3번 문항.
print(f'합계 : {kor.sum()}')
print('-'*27)

# 4번 문항.
dele = np.delete(kor, np.where(kor <= 40))   
print(f'삭제 : {dele}')
print('-'*27)

# 5번 문항.
kor[ kor >=  50 ] = kor[ kor >=  50 ]*1.1
print(f'가산 : {kor}')
print('-'*27)

# 6번 문항.
print(f'Top5 : {np.sort(kor)[::-1][0:5]}')
print('-'*27)

# 7번 문항.
for x, y in zip(kor, np.where(kor >= 70, '합격', '불합격')):
    print(f'점수 : {x}점 여부 : {y}')

< 결과 >
조건 : [60 55 70]
---------------------------
평균 : 54.167
---------------------------
합계 : 325
---------------------------
삭제 : [60 55 70 90]
---------------------------
가산 : [66 60 77 30 20 99]
---------------------------
Top5 : [99 77 66 60 30]
---------------------------
점수 : 66점 여부 : 불합격
점수 : 60점 여부 : 불합격
점수 : 77점 여부 : 합격
점수 : 30점 여부 : 불합격
점수 : 20점 여부 : 불합격
점수 : 99점 여부 : 합격
