In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

#### ndarray 객체의 멤버함수 + np의 함수<br>
np의 함수

In [9]:
arr.sum(), np.sum(arr)         # 합

165

In [12]:
arr.mean(), np.mean(arr)      # 평균

33.0

In [16]:
arr.max(), np.max(arr)       # 최대값

(55, 55)

In [17]:
arr.min(), np.min(arr)      # 최소값

(11, 11)

In [20]:
arr.argmax(), np.argmax(arr)  # 가장 큰 값의 index -> 즉 55의 인덱스 값을 나타낸다.

(4, 4)

In [21]:
arr.argmin(), np.argmin(arr)  # 가장 작은 값의 index -> 즉 11의 인덱스 값을 나타낸다.

(0, 0)

In [25]:
arr.std(), np.std(arr)  # 표준편차

(15.556349186104045, 15.556349186104045)

In [28]:
np.median(arr)         # 중앙값

33.0

In [30]:
np.quantile(arr, 0.5)                 # 데이터를 정렬했을 떄 50% 해당값 

33.0

In [32]:
np.quantile(arr, [0.25,0.5,0.75])    # 4분위수 값 (Q1,Q2,Q3)

array([22., 33., 44.])

In [33]:
np.percentile(arr, [25,50,75])      # np.quantile와는 단위의 차이만 존재

array([22., 33., 44.])

In [71]:
# 연습문제
3. 국어점수가 50점이상 80이하인 값을 구하시요
4. 국어점수의 평균을 구하시요.
5. 국어점수의 총합을 구하시요.
6. 국어점수가 40점이하인 데이터를 삭제하시요
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하시요.
8. 국어점수 top5를 구하시요
9. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
아래와 같이 출력하시요

60 '불합격'
55 '불합격'
kor = np.array( [60,55,70,30,20,90])
kor

SyntaxError: invalid syntax (<ipython-input-71-c3c81364e073>, line 2)

In [41]:
np.max(kor),kor[kor>80]

(90, array([90]))

In [96]:
kor = np.array( [60,55,70,30,20,90])
kor

kor[(kor>49.9) & (kor<80.1)]
kor.mean()   # 4.
kor.sum()   # 5.
np.delete(kor, np.where(kor<=40))   #6.
kor[ kor >=  50 ] = kor[ kor >=  50 ]*1.1     # 7.
np.sort(kor)[-1::-1][0:5]   # 8.
for x, y in zip(kor,np.where(kor >= 70, '합격', '불합격')):
    print(x,y)


66 불합격
60 불합격
77 합격
30 불합격
20 불합격
99 합격
